import type { ProblemDetail } from './types';

const BASE_URL = `${import.meta.env.VITE_API_BASE_URL ?? ''}/api/v1`;

/**
 * Every non-2xx the API can return, carrying the RFC 9457 body (§0.7) rather than just a status.
 * Forms read {@link fieldErrors} off it to put a message against the right input; everything else
 * shows {@link ProblemDetail.detail}, which is already written for a human.
 */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly problem: ProblemDetail,
  ) {
    super(problem.detail ?? problem.title ?? `Request failed with ${status}`);
    this.name = 'ApiError';
  }

  get isUnauthorized(): boolean {
    return this.status === 401;
  }
}

/**
 * Maps a ProblemDetail onto the form fields it came from.
 *
 * <p>When `errors[]` names exactly one field, that field gets `detail` — the sentence the server
 * wrote for a person ("Cannot sell 50 of AAPL; holding is 12.") rather than the terse per-field
 * note. With several fields at fault there is no single sentence to spread across them, so each
 * gets its own message.
 */
export function fieldErrors(problem: ProblemDetail): Record<string, string> {
  const entries = problem.errors ?? [];
  if (entries.length === 1 && problem.detail) {
    return { [entries[0].field]: problem.detail };
  }
  return Object.fromEntries(entries.map((entry) => [entry.field, entry.message]));
}

let tokenProvider: () => string | null = () => null;

/** Set once at start-up by the auth layer; keeps this module free of React. */
export function setTokenProvider(provider: () => string | null): void {
  tokenProvider = provider;
}

/**
 * A `FormData` body must NOT carry a hand-written `Content-Type`. `multipart/form-data` is
 * meaningless without the boundary token that separates the parts, and that token is generated by
 * `fetch` when it serialises the body — setting the header ourselves overwrites the complete one
 * `fetch` would have written with a boundary-less one, and the server then finds no parts at all.
 * Leaving the header off entirely is what lets `fetch` fill it in correctly.
 */
function contentTypeFor(body: BodyInit | null | undefined): Record<string, string> {
  if (body === null || body === undefined || body instanceof FormData) {
    return {};
  }
  return { 'Content-Type': 'application/json' };
}

export async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const token = tokenProvider();
  const response = await fetch(`${BASE_URL}${path}`, {
    ...init,
    headers: {
      Accept: 'application/json',
      ...contentTypeFor(init.body),
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...init.headers,
    },
  });

  if (response.status === 204) {
    return undefined as T;
  }

  const body = await response.json().catch(() => null);
  if (!response.ok) {
    throw new ApiError(response.status, (body as ProblemDetail) ?? { status: response.status });
  }
  return body as T;
}

export function query(params: Record<string, string | number | boolean | null | undefined>): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== null && value !== undefined && value !== '') {
      search.set(key, String(value));
    }
  }
  const encoded = search.toString();
  return encoded ? `?${encoded}` : '';
}
